In [ ]:
#numpy library
import numpy as np
energy_consumption=np.array([1200, 3400, 2900, 1800, 2500])
print("\nEnergy Consumption:")
print(energy_consumption)


Energy Consumption:
[1200 3400 2900 1800 2500]


In [ ]:
import numpy as np
mylist=[[1,2,3],[4,5,6],[7,8,9]]
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

np.array():
np.random.randint(0,10,1):
np.unique():
np.dot():
np.power(a,2):
np.sqrt(a):
np.ones():
np.zeros():
np.max():
np.arange(10):

In [ ]:
np.random.rand(4,4)

array([[0.74914332, 0.82317324, 0.32254141, 0.5915032 ],
       [0.63183907, 0.32665744, 0.28941892, 0.87247594],
       [0.36258586, 0.14892574, 0.67794415, 0.14893048],
       [0.77928764, 0.11552002, 0.17829851, 0.73622453]])

In [ ]:
total_consumption=np.sum(energy_consumption)
print(f"Total Energy Consumption:{total_consumption}MWh")
print(total_consumption)

Total Energy Consumption:11800MWh
11800


In [ ]:
mean_consumption=np.mean(energy_consumption)
print(f"\nMean Energy Consumption:{mean_consumption:.2f}MWh")


Mean Energy Consumption:2360.00MWh


In [ ]:
std_deviation=np.std(energy_consumption)
print(f"\nStandard Deviation of Energy Consumption:{std_deviation:.2f}MWh")



Standard Deviation of Energy Consumption:781.28MWh


In [ ]:
reshaped_array=energy_consumption.reshape(5,1)
print("\nReshaped Energy Consumption Array(5x1):")
print(reshaped_array)



Reshaped Energy Consumption Array(5x1):
[[1200]
 [3400]
 [2900]
 [1800]
 [2500]]
